"""hostel phases 2 to 5"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='bb2c3d4e5f6a'; down_revision='aa1b2c3d4e5f'; branch_labels=None; depends_on=None
U=lambda: postgresql.UUID(as_uuid=True)
T=lambda: sa.DateTime(timezone=True)
def audit(): return [sa.Column('created_at',T(),server_default=sa.text('now()')),sa.Column('updated_at',T(),server_default=sa.text('now()'))]
def upgrade():
 op.create_table('hostel_visitors',sa.Column('id',U(),primary_key=True),sa.Column('student_id',U(),sa.ForeignKey('students.id'),nullable=False),sa.Column('visitor_name',sa.String(255),nullable=False),sa.Column('relation',sa.String(100)),sa.Column('phone',sa.String(30),nullable=False),sa.Column('check_in_time',T(),nullable=False),sa.Column('check_out_time',T()),sa.Column('approved_by',U(),sa.ForeignKey('users.id'),nullable=False),*audit())
 op.create_table('hostel_fee_structures',sa.Column('id',U(),primary_key=True),sa.Column('fee_type',sa.String(100),nullable=False),sa.Column('amount',sa.Numeric(10,2),nullable=False),sa.Column('academic_year',sa.String(50),nullable=False),sa.Column('description',sa.Text()),*audit(),sa.UniqueConstraint('fee_type','academic_year',name='uq_hostel_fee_type_year'))
 op.create_table('hostel_fee_invoices',sa.Column('id',U(),primary_key=True),sa.Column('student_id',U(),sa.ForeignKey('students.id'),nullable=False),sa.Column('hostel_fee_id',U(),sa.ForeignKey('hostel_fee_structures.id'),nullable=False),sa.Column('invoice_date',sa.Date(),nullable=False),sa.Column('due_date',sa.Date(),nullable=False),sa.Column('amount',sa.Numeric(10,2),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='PENDING'),*audit())
 op.create_table('hostel_payments',sa.Column('id',U(),primary_key=True),sa.Column('invoice_id',U(),sa.ForeignKey('hostel_fee_invoices.id'),nullable=False),sa.Column('payment_date',sa.Date(),nullable=False),sa.Column('amount_paid',sa.Numeric(10,2),nullable=False),sa.Column('payment_method',sa.String(30),nullable=False),sa.Column('transaction_no',sa.String(100)),sa.Column('receipt_no',sa.String(100)),sa.Column('remarks',sa.Text()),*audit())
 for n,cols in [('mess_menu',[sa.Column('meal_type',sa.String(30),nullable=False),sa.Column('menu_date',sa.Date(),nullable=False),sa.Column('breakfast',sa.Text()),sa.Column('lunch',sa.Text()),sa.Column('dinner',sa.Text()),sa.Column('created_by',U(),sa.ForeignKey('users.id'),nullable=False)]),('mess_expenses',[sa.Column('expense_date',sa.Date(),nullable=False),sa.Column('category',sa.String(100),nullable=False),sa.Column('description',sa.Text()),sa.Column('amount',sa.Numeric(10,2),nullable=False)]),('mess_collections',[sa.Column('student_id',U(),sa.ForeignKey('students.id'),nullable=False),sa.Column('amount',sa.Numeric(10,2),nullable=False),sa.Column('collection_date',sa.Date(),nullable=False),sa.Column('payment_method',sa.String(30),nullable=False),sa.Column('received_by',U(),sa.ForeignKey('users.id'),nullable=False)]),('mess_attendance',[sa.Column('student_id',U(),sa.ForeignKey('students.id'),nullable=False),sa.Column('meal_type',sa.String(30),nullable=False),sa.Column('attendance_date',sa.Date(),nullable=False),sa.Column('status',sa.String(20),nullable=False)]),('maintenance_requests',[sa.Column('requested_by',U(),sa.ForeignKey('students.id'),nullable=False),sa.Column('room_id',U(),sa.ForeignKey('hostel_rooms.id'),nullable=False),sa.Column('issue_type',sa.String(100),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('priority',sa.String(20),server_default='MEDIUM'),sa.Column('status',sa.String(20),server_default='OPEN'),sa.Column('requested_on',T(),server_default=sa.text('now()'))]),('work_orders',[sa.Column('request_id',U(),sa.ForeignKey('maintenance_requests.id'),nullable=False),sa.Column('assigned_to',U(),sa.ForeignKey('users.id'),nullable=False),sa.Column('scheduled_date',sa.Date(),nullable=False),sa.Column('completed_date',sa.Date()),sa.Column('status',sa.String(20),server_default='OPEN')])]: op.create_table(n,sa.Column('id',U(),primary_key=True),*cols,*audit())
def downgrade():
 for n in ['work_orders','maintenance_requests','mess_attendance','mess_collections','mess_expenses','mess_menu','hostel_payments','hostel_fee_invoices','hostel_fee_structures','hostel_visitors']: op.drop_table(n)
